name: Watch Workflow Status
on:
  workflow_run:
    workflows: [ "Deploy" ]
    types: [ completed ]
env:
  WECHAT_WORK_BOT_WEBHOOK: ${{secrets.WECHAT_WORK_BOT_WEBHOOK}}
  MORE_URL: 'https://www.hocgin.top'

jobs:
  on-success:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
      - name: WeChat Work Prepare
        id: wx_prep
        run: |
          echo ::set-output name=wx_created::$(TZ=Asia/Shanghai date -d @`date +%s` "+%Y-%m-%d %H:%M:%S")
          GITHUB_REF=${{github.base_ref}}
          echo ::set-output name=wx_base_ref::$(echo ${GITHUB_REF#refs/heads/})
          GITHUB_REF=${{github.event.ref}}
          echo ::set-output name=wx_target_ref::$(echo ${GITHUB_REF#refs/heads/})
      - name: WeChat Work Notification
        uses: chf007/action-wechat-work@master
        env:
          WECHAT_WORK_BOT_WEBHOOK: ${{env.WECHAT_WORK_BOT_WEBHOOK}}
        with:
          msgtype: markdown
          content: "â˜€ï¸**ã€[${{ github.repository }}](https://github.com/${{ github.repository }})ã€‘** \n
          \n
          ğŸƒ [@${{ github.actor }}](https://github.com/${{ github.actor }})\n
          ğŸ• <font color=\"comment\">${{ steps.wx_prep.outputs.wx_created }}</font> \n
          ğŸ”§ <font color=\"warning\">${{ steps.wx_prep.outputs.wx_base_ref || 'âˆ…' }} -> ${{ steps.wx_prep.outputs.wx_target_ref }}</font> \n
          ğŸ“ <font color=\"comment\"> ${{ github.event.head_commit.message }}</font> \n
          \n
          [æŸ¥çœ‹è¯¦æƒ…](${{ env.MORE_URL }})
          "
  on-failure:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'failure' }}
    steps:
      - name: WeChat Work Prepare
        id: wx_prep
        run: |
          echo ::set-output name=wx_created::$(TZ=Asia/Shanghai date -d @`date +%s` "+%Y-%m-%d %H:%M:%S")
          GITHUB_REF=${{github.base_ref}}
          echo ::set-output name=wx_base_ref::$(echo ${GITHUB_REF#refs/heads/})
          GITHUB_REF=${{github.event.ref}}
          echo ::set-output name=wx_target_ref::$(echo ${GITHUB_REF#refs/heads/})
      - name: WeChat Work Notification
        uses: chf007/action-wechat-work@master
        env:
          WECHAT_WORK_BOT_WEBHOOK: ${{env.WECHAT_WORK_BOT_WEBHOOK}}
        with:
          msgtype: markdown
          content: "ğŸŒ§ï¸**ã€[${{ github.repository }}](https://github.com/${{ github.repository }})ã€‘** \n
          \n
          ğŸƒ [@${{ github.actor }}](https://github.com/${{ github.actor }})\n
          ğŸ• <font color=\"comment\">${{ steps.wx_prep.outputs.wx_created }}</font> \n
          ğŸ”§ <font color=\"warning\">${{ steps.wx_prep.outputs.wx_base_ref || 'âˆ…' }} -> ${{ steps.wx_prep.outputs.wx_target_ref }}</font> \n
          ğŸ“ <font color=\"comment\"> ${{ github.event.head_commit.message }}</font> \n
          \n
          [æŸ¥çœ‹è¯¦æƒ…](${{ env.MORE_URL }})
          "
